---
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
    secrets:
       numa-numa-token:
        required: true

  jobs:
    bugfixing:
      runs-on: ubuntu-latest
      steps:
        - name: Set up Docker Context for Buildx
          id: buildx-context
          run: |
            docker context create builders        
        - name: Docker Setup Buildx
          uses: docker/setup-buildx-action@v3
          with:
            version: latest
            endpoint: builders
            buildkitd-flags: --debug
        - name: docker login
          uses: docker/login-action@v3.3.0
          with:
            registry: ghcr.io
            username: easir
            password: ${{ secrets.GH_TOKEN }}
        - name: bugfixing the service!
          run: |
            set -x
            repo="ghcr.io/${{ github.repository }}"
            epoch=$(date +%s)
            docker buildx imagetools inspect $repo:${{github.event.inputs.tag}}
            docker buildx imagetools create --tag $repo:sad-prod-$epoch $repo:${{github.event.inputs.tag}}
            docker buildx imagetools create --tag $repo:sad-release-candidate $repo:${{github.event.inputs.tag}}

