name: Cleanup caches by a branch
on:
  workflow_call:
    secrets:
      numa-numa-token:
        required: true
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        run: |
           gh extension install actions/gh-actions-cache
           
           echo "Fetching list of cache key"
           cacheKeysForPR=$(gh actions-cache list -R $REPO -B $BRANCH -L 100 | cut -f 1 )
           
           ## Setting this to not fail the workflow while deleting cache keys.
           set +e
           echo "Deleting caches..."
           for cacheKey in $cacheKeysForPR
           do
               gh actions-cache delete $cacheKey -R $REPO -B $BRANCH --confirm
           done
           echo "Done"
        env:
          GH_TOKEN: ${{ secrets.numa-numa-token }}
          REPO: ${{ github.repository }}
          BRANCH: refs/pull/${{ github.event.pull_request.number }}/merge

      - name: summary
        run: |
          echo REPO: ${{ github.repository }} >> $GITHUB_STEP_SUMMARY
          echo "IMAGE TAGS : ${{ github.event.pull_request.number }} >> $GITHUB_STEP_SUMMARY"
