---
on:
  workflow_call:
    secrets:
       numa-numa-token:
        required: true

jobs:
  setup_variables:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: pull code # pull repo apki
        env:
          GITHUB_TOKEN: ${{ secrets.numa-numa-token }}
        uses: actions/checkout@v4
      - name: pull flux-prod
        env:
          GITHUB_TOKEN: ${{ secrets.numa-numa-token }}
        with:
          repository: easir/flux-prod
          path: flux-prod
          token: ${{ secrets.numa-numa-token }}
        uses: actions/checkout@v4
      - name: docker login
        env:
          GITHUB_TOKEN: ${{ secrets.numa-numa-token }}
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: easir
          password: ${{ secrets.numa-numa-token }}
      - name: Set up Docker Context for Buildx
        env:
          GITHUB_TOKEN: ${{ secrets.numa-numa-token }}
        id: buildx-context
        run: |
          docker context create builders
      - name: Docker Setup Buildx
        env:
          GITHUB_TOKEN: ${{ secrets.numa-numa-token }}
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
          endpoint: builders
          platforms: "linux/arm64,linux/amd64"
          buildkitd-flags: --debug
      - name: job
        run: |
          env
          echo _____________________
          echo ${{ github.repository }}
      - name: get the digests of images
        env:
          GITHUB_TOKEN: ${{ secrets.numa-numa-token }}      
        if: ${{ github.repository != 'easir/pdf' }}
        run: |
          ls -al
          pwd 
          app=$(echo {{$github.repository}} | cut -d "/" -f 2)
          echo $app
          ls -al flux-prod
          cat flux-prod/clusters/skoda/staging/helm-$app.yaml | yq '.spec.values.image.repository'
          repo=$(cat flux-prod/clusters/skoda/staging/helm-$app.yaml 2>/dev/null | yq '.spec.values.image.repository')
          tag=$(cat flux-prod/clusters/skoda/staging/helm-$app.yaml 2>/dev/null | yq '.spec.values.image.tag')
          prodrepo=$(cat flux-prod/clusters/skoda/production/helm-$app.yaml 2>/dev/null | yq '.spec.values.image.repository')
          prodtag=$(cat flux-prod/clusters/skoda/production/helm-$app.yaml 2>/dev/null | yq '.spec.values.image.tag')
          current_rc_image=$repo:$(docker buildx imagetools inspect $repo:sad-release-candidate --format "{{json .Manifest}}" | jq -r '.digest | split(":")[1]')
          next_rc_image=$repo:$(docker buildx imagetools inspect $repo:$tag --format "{{json .Manifest}}" | jq -r '.digest | split(":")[1]')
          prod_image=$prodrepo:$(docker buildx imagetools inspect $prodrepo:$prodtag --format "{{json .Manifest}}" | jq -r '.digest | split(":")[1]')
          echo $repo $tag $prodrepo $prodtag
          echo "CURRENT RC $current_rc_image........... NEXT: $next_rc_image .... PROD: $prod_image"

      - name: pdf is special
        if: ${{ github.repository == 'easir/pdf' }}
        run: |
          echo yeah - mom said pdf is special
          repo=$(cat flux-prod/clusters/skoda/staging/helm-pdf.yaml 2>/dev/null | yq '.spec.values.Image')
          tag=$(cat flux-prod/clusters/skoda/staging/helm-pdf.yaml 2>/dev/null | yq '.spec.values.ImageTag')
          #remove this echo before going real
          #echo docker buildx imagetools create --tag $repo:sad-prod-$epoch $repo:sad-release-candidate
          prodrepo=$(cat flux-prod/clusters/skoda/production/helm-pdf.yaml 2>/dev/null | yq '.spec.values.Image')
          prodtag=$(cat flux-prod/clusters/skoda/production/helm-pdf.yaml 2>/dev/null | yq '.spec.values.ImageTag')

      - name: sprawdz staging oraz prod sha oraz tag jaki jest aktualnie w flux-prod
        # outputs:
        #   prod-digest:
        #   current-release-candidate-digest:
        #   staging-digest:
        run: |
          cat flux-prod/clusters/skoda/staging/helm-auth-bff.yaml
      - name: porównaj
        run: echo porownalem
